apiVersion: apps/v1
kind: Deployment
metadata:
  name: drive-service
  namespace: prpo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drive-service
  template:
    metadata:
      labels:
        app: drive-service
    spec:
      containers:
      - name: drive-service
        image: prporegistry.azurecr.io/drive-service:accc4aafb3268a79513258f55c875c34253c988e
        ports:
        - containerPort: 8080
        env:
        - name: JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: JWT_TOKEN

      
---
apiVersion: v1
kind: Service
metadata:
  name: drive-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: drive-service
  ports:
    - port: 8080
      targetPort: 8080




